### ISSUE TITLE
User is prompted for authentication even when http_auth_type is set to 'none'

### ISSUE THREAD

**Issue by lohengrin332** [timbunce/WebAPI-DBIC#26]
The provided examples show that setting either the environment variable ```WEBAPI_DBIC_HTTP_AUTH_TYPE=none``` or ```resource_default_args->{http_auth_type} = 'none'``` during WebApp instantiation will override the default auth type of 'basic'.  This is not functioning as expected.  This can only be overridden currently by changing [WebAPI::DBIC::Resource::Base](https://github.com/timbunce/WebAPI-DBIC/blob/master/lib/WebAPI/DBIC/Resource/Base.pm#L21).

**Comment by timbunce** [comment]
Fixed in master (30e440e) I believe.
