### ISSUE TITLE
WAPID pre-pending path on links->href

### ISSUE THREAD

**Issue by lohengrin332** [timbunce/WebAPI-DBIC#27]
With WAPID mounted on an API path:

    my $app = WebAPI::DBIC::WebApp->new({...});
    builder {
        mount '/WAPID' => $app;
    };

Links are returned prepended with '/WAPID'.  Given the query string ```/WAPID/artists?prefetch=cds```, the following JSON is returned:

    {
        "linked": {
            "cds": [
                {
                    "href": "/WAPID/cds/1",
                    ...
                },
                ...
            ]
        },
        "links": {
            "artists.cds": {
                "href": "/WAPID/cds?me.artist_id={cds.id}",
                "type": "cds"
            }
        },
        "artists": [
            {
                "href": "/WAPID/artists/1",
                "links": {
                    "cds": [...]
                },
                ...
            }
        ]
    }

**Comment by timbunce** [comment]
I'm not clear if you're describing current behaviour as a bug or describing the desired behaviour.
It seems like you're saying that `href` values should _not_ contain the path prefix, but that would be broken I think: hrefs should use usable URLs.

If you think href's URLs _shouldn't_ include the path prefix I'd appreciate some links to docs that support that.

**Comment by lohengrin332** [comment]
This was a human to human miscommunication.  Please disregard.
