### ISSUE TITLE
DBI Exception when accessing /<route>/<id> and also using a prefetch

### ISSUE THREAD

**Issue by lohengrin332** [timbunce/WebAPI-DBIC#28]
Given the following URL:

    /artists/1?prefetch~json={"cds":"tracks"}

The following SQL is generated:

    SELECT <columns>
    FROM artists me
    JOIN cds cd ON cd.artist_id = me.id
    JOIN tracks track ON track.cd_id = cd.id
    WHERE id = '1'
    ORDER BY me.id ASC
    LIMIT '30'

And the following error is encountered:

    ERROR: DBI Exception: DBD::Pg::st execute failed: ERROR:  column reference "id" is ambiguous

**Comment by lohengrin332** [comment]
The same error occurs with the following URL:

    /artists/1?prefetch=cds

**Comment by ungrim97** [comment]
@lohengrin332 I have been unable to replicate this issue using the test schema. 

This is the cURL that I made:
> `127.0.0.1 - - [15/Jan/2015:17:28:01 +0000] "GET /webapi-dbic/artist/1?prefetch=cds HTTP/1.1" 200 1238 "-" "curl/7.35.0"`

And the resulting SELECT statement:
> `SELECT me.artistid, me.name, me.rank, me.charfield, cds.cdid, cds.artist, cds.title, cds.year, cds.genreid, cds.single_track FROM (SELECT me.artistid, me.name, me.rank, me.charfield FROM artist me WHERE ( me.artistid = ? ) ORDER BY me.artistid ASC LIMIT ?) me LEFT JOIN cd cds ON cds.artist = me.artistid WHERE ( me.artistid = ? ) ORDER BY me.artistid ASC: '1', '30', '1'`

Can you give me more details about the version of DBIC, DBI and SQL::Abstract your using and the database schema information?

**Comment by lohengrin332** [comment]
@ungrim97 Here are the version numbers you've requested:

DBIC: 0.082810
DBI: 1.620
SQL::Abstract: 1.81

My real life example involves several tables where the identity column is called simply 'id' on each table.  This is my URL: ```/master_territories/1?prefetch=cities```, and this is the SQL I'm getting, with the column names removed:

    SELECT me.<columns>, cities.<columns>
    FROM (
        SELECT me.<columns>
        FROM master_territories me
        WHERE ( id = 1 )
        ORDER BY me.id ASC
    ) me
    LEFT JOIN cities cities ON cities.master_territory_id = me.id
    WHERE ( id = 1 )
    ORDER BY me.id ASC

master_territories::cities is a 1::many relationship.  I get simpler SQL but the same end result with a many::1 relationship, such as master_territories::license_types:

    SELECT me.<columns>, license_type.<columns>
    FROM master_territories me
    JOIN license_types license_type ON license_type.id = me.license_type_id
    WHERE ( id = ? )
    ORDER BY me.id ASC

Thanks for your help.

**Comment by ungrim97** [comment]
@lohengrin332 I have now been able to replicate this issue. It is specific to the jsonapi format and to when the primary column is called id.

I should have a fix in the next day or so.

**Comment by ungrim97** [comment]
@lohengrin332 this should be resolved in 987dc2e

**Comment by lohengrin332** [comment]
@ungrim97 that fixed it, thank you much.
