### ISSUE TITLE
Fatal Exception when using an array-based prefetch~json

### ISSUE THREAD

**Issue by lohengrin332** [timbunce/WebAPI-DBIC#29]
Given the following URL path:

    /artists?prefetch~json=[{"cds":"tracks"}, "producer"]

Results in the following exception:

    Exception: Not a HASH reference at WebAPI-DBIC/lib/WebAPI/DBIC/Resource/Role/DBICParams.pm line 144.

**Comment by ungrim97** [comment]
this should be fixed in 4f59af2594e481064bd98fc0968c177ef2948026

**Comment by timbunce** [comment]
Great. Many thanks @ungrim97!

**Comment by lohengrin332** [comment]
I've confirmed that this fixes my issue.  Thanks, @ungrim97!
